version: "3"

services:
  db:
    image: postgres:10.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - DATABASE_URL
